/**
 * @file mineralSourcing.ts
 * 
 * Sourcing & Midnight Sync Pipeline for Minerals & Physical Mineralogy Data.
 * Sourced from open authoritative datasets:
 * - International Mineralogical Association (IMA) Master Species
 * - RRUFF Mineralogy Database (University of Arizona)
 * - Macrostrat Lithology Associations
 */

import { refDb } from "../db/refDb";
import { minerals, InsertMineral } from "../db/schema";
import { eq } from "drizzle-orm";

export const CURATED_MINERAL_DATASET: Omit<InsertMineral, "id" | "createdAt" | "updatedAt">[] = [
  // --- NATIVE ELEMENTS ---
  {
    name: "Diamond",
    formula: "C",
    crystalSystem: "Isometric",
    mineralClass: "Native Elements",
    mohsHardnessMin: 10,
    mohsHardnessMax: 10,
    specificGravity: 3.52,
    luster: "Adamantine",
    color: "Colorless, yellow, brown, blue, pink, black",
    streak: "White",
    cleavage: "Perfect {111} in 4 directions",
    fracture: "Conchoidal",
    opticalProperties: "Isotropic (n = 2.417)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Extreme hardness (10), octahedral crystal habit, adamantine luster, thermal conductivity",
    commonAssociatedRocks: "Kimberlite, Lamproite, Alluvial gravels",
    industrialUses: "Gemstones, High-speed cutting tools, Heat sinks, Laser optics",
    occurrence: "High-pressure mantle melting brought to crust via diatreme pipes",
    imageUrl: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040003",
  },
  {
    name: "Gold",
    formula: "Au",
    crystalSystem: "Isometric",
    mineralClass: "Native Elements",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 3.0,
    specificGravity: 19.3,
    luster: "Metallic",
    color: "Golden yellow to brass yellow",
    streak: "Golden yellow",
    cleavage: "None",
    fracture: "Hackly",
    opticalProperties: "Opaque",
    imaStatus: "Approved",
    tenacity: "Highly malleable and ductile",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Extreme density (19.3), sectility, golden streak, insolubility in nitric acid",
    commonAssociatedRocks: "Hydrothermal quartz veins, Placers, Greenstone belts, Skarns",
    industrialUses: "Monetary reserves, Electronics, Corrosion-resistant plating, Jewelry",
    occurrence: "Epithermal and orogenic gold deposits, sedimentary placer concentrates",
    imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=600&q=80",
    rruffId: "R060136",
  },
  {
    name: "Silver",
    formula: "Ag",
    crystalSystem: "Isometric",
    mineralClass: "Native Elements",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 3.0,
    specificGravity: 10.5,
    luster: "Metallic",
    color: "Silver-white, tarnishes black (acanthite coating)",
    streak: "Silver-white to shiny gray",
    cleavage: "None",
    fracture: "Hackly",
    opticalProperties: "Opaque",
    imaStatus: "Approved",
    tenacity: "Malleable and ductile",
    diaphaneity: "Opaque",
    diagnosticFeatures: "High electrical conductivity, metallic luster, silver streak, solubility in HNO3",
    commonAssociatedRocks: "Epithermal veins, Volcanogenic massive sulfide (VMS), Carbonate-hosted Pb-Zn",
    industrialUses: "Photovoltaic solar cells, High-end electronics, Battery electrodes, Bullion",
    occurrence: "Hydrothermal epithermal veins and supergene enrichment zones",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    rruffId: "R070258",
  },
  {
    name: "Copper",
    formula: "Cu",
    crystalSystem: "Isometric",
    mineralClass: "Native Elements",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 3.0,
    specificGravity: 8.94,
    luster: "Metallic",
    color: "Copper-red, tarnishes brown to green (malachite patina)",
    streak: "Metallic copper-red",
    cleavage: "None",
    fracture: "Hackly",
    opticalProperties: "Opaque",
    imaStatus: "Approved",
    tenacity: "Malleable and ductile",
    diaphaneity: "Opaque",
    diagnosticFeatures: "High specific gravity, bright copper streak, ductile hackly wire habit",
    commonAssociatedRocks: "Basalt amygdules, Sandstone-hosted copper, Porphyry copper supergene zones",
    industrialUses: "Electrical wiring, Renewable energy grid, Telecommunications, Brass/Bronze alloys",
    occurrence: "Hydrothermal precipitation and basalt flow vesicles",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80",
    rruffId: "R060010",
  },
  {
    name: "Graphite",
    formula: "C",
    crystalSystem: "Hexagonal",
    mineralClass: "Native Elements",
    mohsHardnessMin: 1.0,
    mohsHardnessMax: 2.0,
    specificGravity: 2.26,
    luster: "Submetallic to earthy",
    color: "Iron black to dark steel-gray",
    streak: "Black to dark gray (marks paper easily)",
    cleavage: "Perfect basal {0001}",
    fracture: "Uneven",
    opticalProperties: "Opaque, strong pleochroism in polished section",
    imaStatus: "Approved",
    tenacity: "Flexible in thin sheets, greasy feel",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Extremely soft (1-2), greasy feel, marks paper and fingers, conducts electricity",
    commonAssociatedRocks: "Graphitic schist, Gneiss, Marble, Pegmatite",
    industrialUses: "EV Lithium-ion battery anodes, Refractory crucibles, Solid lubricants",
    occurrence: "High-grade regional metamorphism of organic-rich carbonaceous sediments",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    rruffId: "R050017",
  },
  {
    name: "Sulfur",
    formula: "S8",
    crystalSystem: "Orthorhombic",
    mineralClass: "Native Elements",
    mohsHardnessMin: 1.5,
    mohsHardnessMax: 2.5,
    specificGravity: 2.07,
    luster: "Resinous to greasy",
    color: "Bright yellow, greenish yellow",
    streak: "White to pale yellow",
    cleavage: "Imperfect {001}, {110}",
    fracture: "Conchoidal to uneven",
    opticalProperties: "Biaxial (+) n=1.95-2.24",
    imaStatus: "Approved",
    tenacity: "Brittle to sectile",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Bright yellow color, low melting point (115°C), sulfurous odor upon burning",
    commonAssociatedRocks: "Evaporites, Volcanic fumaroles, Salt dome caprocks",
    industrialUses: "Sulfuric acid production, Agricultural fertilizers, Rubber vulcanization",
    occurrence: "Volcanic exhalations and bacterial reduction of gypsum in caprocks",
    rruffId: "R040056",
  },

  // --- SILICATES (Rock-Forming Minerals) ---
  {
    name: "Quartz",
    formula: "SiO2",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Silicates",
    mohsHardnessMin: 7.0,
    mohsHardnessMax: 7.0,
    specificGravity: 2.65,
    luster: "Vitreous",
    color: "Colorless, white, purple (amethyst), smoky, yellow (citrine), rose",
    streak: "White",
    cleavage: "None (indistinct rhombohedral)",
    fracture: "Conchoidal",
    opticalProperties: "Uniaxial (+) nw=1.544, ne=1.553",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Hardness 7, conchoidal fracture, glassy luster, lack of cleavage, hexagonal prism with pyramid terminations",
    commonAssociatedRocks: "Granite, Rhyolite, Sandstone, Quartzite, Gneiss, Hydrothermal veins",
    industrialUses: "Glassmaking, Semiconductors, Quartz crystal resonators, Foundry sand",
    occurrence: "Ubiquitous felsic igneous, sedimentary clastic, and regional metamorphic rocks",
    imageUrl: "https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040031",
  },
  {
    name: "Orthoclase (Potassium Feldspar)",
    formula: "KAlSi3O8",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 6.0,
    mohsHardnessMax: 6.0,
    specificGravity: 2.56,
    luster: "Vitreous to pearly",
    color: "Pink, salmon red, flesh, white, gray",
    streak: "White",
    cleavage: "Perfect at 90° {001} and {010}",
    fracture: "Uneven to conchoidal",
    opticalProperties: "Biaxial (-) na=1.518, nb=1.522, ng=1.525",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to sub-translucent",
    diagnosticFeatures: "Hardness 6 (Mohs scale index), pinkish color, two perfect cleavage planes meeting at 90 degrees",
    commonAssociatedRocks: "Granite, Syenite, Pegmatite, Gneiss, Arkose",
    industrialUses: "Ceramics manufacture, Glass flux, Scouring powders",
    occurrence: "Dominant mineral in felsic plutonic and high-grade metamorphic rocks",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040008",
  },
  {
    name: "Albite (Plagioclase)",
    formula: "NaAlSi3O8",
    crystalSystem: "Triclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 6.0,
    mohsHardnessMax: 6.5,
    specificGravity: 2.62,
    luster: "Vitreous to pearly",
    color: "White, gray, pale greenish, bluish iridescent (peristerite)",
    streak: "White",
    cleavage: "Perfect {001} and {010} at ~86°",
    fracture: "Uneven",
    opticalProperties: "Biaxial (+) na=1.527, nb=1.532, ng=1.538",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Polysynthetic polysynthetic albite twinning striations on cleavage surfaces",
    commonAssociatedRocks: "Granite, Pegmatite, Diorite, Greenschist, Hydrothermal albitite",
    industrialUses: "Ceramic glazes, Fluxes, Functional filler",
    occurrence: "Felsic to intermediate igneous and low-grade metamorphic rocks",
    rruffId: "R040015",
  },
  {
    name: "Anorthite (Plagioclase)",
    formula: "CaAl2Si2O8",
    crystalSystem: "Triclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 6.0,
    mohsHardnessMax: 6.5,
    specificGravity: 2.76,
    luster: "Vitreous",
    color: "White, grayish, reddish",
    streak: "White",
    cleavage: "Perfect {001} and {010}",
    fracture: "Uneven",
    opticalProperties: "Biaxial (-) na=1.575, nb=1.583, ng=1.589",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "High refractive index compared to albite, polysynthetic twinning, association with mafic minerals",
    commonAssociatedRocks: "Gabbro, Basalt, Anorthosite, Lunar highlands regolith",
    industrialUses: "Refractories, Ceramic matrix composites",
    occurrence: "Primitive mafic magma crystallization and layered intrusions",
    rruffId: "R050030",
  },
  {
    name: "Biotite",
    formula: "K(Mg,Fe)3(AlSi3O10)(OH,F)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 3.0,
    specificGravity: 3.09,
    luster: "Vitreous to splendent",
    color: "Dark brown, greenish brown, jet black",
    streak: "White to gray",
    cleavage: "Perfect basal {001} into flexible elastic sheets",
    fracture: "Uneven",
    opticalProperties: "Biaxial (-) strong pleochroism (straw yellow to dark brown)",
    imaStatus: "Approved",
    tenacity: "Elastic",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Dark sheet silicate (mica), perfect basal cleavage peels into flexible dark sheets",
    commonAssociatedRocks: "Granite, Diorite, Mica schist, Gneiss",
    industrialUses: "Geochronological dating (K-Ar and Ar-Ar), drilling mud additive",
    occurrence: "Igneous felsic-intermediate melts and regional metamorphism",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040039",
  },
  {
    name: "Muscovite",
    formula: "KAl2(AlSi3O10)(OH)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 2.0,
    mohsHardnessMax: 2.5,
    specificGravity: 2.82,
    luster: "Vitreous to pearly / silky",
    color: "Colorless, white, silvery, pale brown, greenish",
    streak: "White",
    cleavage: "Perfect basal {001} (micaceous)",
    fracture: "Splintery",
    opticalProperties: "Biaxial (-) na=1.552, nb=1.582, ng=1.587",
    imaStatus: "Approved",
    tenacity: "Highly elastic",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Colorless to silvery sheets with extraordinary elasticity and dielectric insulation",
    commonAssociatedRocks: "Pegmatite, Muscovite granite, Phyllite, Mica schist, Gneiss",
    industrialUses: "Electrical and thermal insulator, Cosmetics (pearlescent shine), Joint compounds",
    occurrence: "Peraluminous granitic melts and medium-grade metapelites",
    rruffId: "R040019",
  },
  {
    name: "Augite (Clinopyroxene)",
    formula: "(Ca,Na)(Mg,Fe,Al,Ti)(Si,Al)2O6",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 5.5,
    mohsHardnessMax: 6.0,
    specificGravity: 3.4,
    luster: "Vitreous to dull",
    color: "Dark green, brownish green, jet black",
    streak: "Light green to grayish white",
    cleavage: "Prismatic {110} at ~87° and 93°",
    fracture: "Uneven to conchoidal",
    opticalProperties: "Biaxial (+) na=1.68, nb=1.69, ng=1.71",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Stubby 8-sided prismatic crystals, ~90° pyroxene cleavage intersections, dark green/black color",
    commonAssociatedRocks: "Basalt, Gabbro, Diabase, Pyroxenite, Peridotite",
    industrialUses: "Flux, Petrological temperature-pressure geothermobarometry indicator",
    occurrence: "Mafic and ultramafic volcanic and plutonic systems",
    rruffId: "R040058",
  },
  {
    name: "Hornblende (Amphibole)",
    formula: "(Ca,Na)2–3(Mg,Fe,Al)5(Al,Si)8O22(OH,F)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 5.0,
    mohsHardnessMax: 6.0,
    specificGravity: 3.23,
    luster: "Vitreous to silky",
    color: "Dark green, dark brown, jet black",
    streak: "Pale gray to greenish white",
    cleavage: "Perfect prismatic {110} at 56° and 124°",
    fracture: "Uneven",
    opticalProperties: "Biaxial (-) strong pleochroism (green to olive brown)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Elongated prismatic or bladed crystals with characteristic 56°/124° diamond-profile amphibole cleavage",
    commonAssociatedRocks: "Andesite, Diorite, Granodiorite, Amphibolite, Hornblende schist",
    industrialUses: "Dimension stone, Geochronology, Petrogenesis modeling",
    occurrence: "Hydrous intermediate igneous rocks and medium-to-high grade amphibolite facies metamorphism",
    rruffId: "R040046",
  },
  {
    name: "Forsterite (Olivine)",
    formula: "Mg2SiO4",
    crystalSystem: "Orthorhombic",
    mineralClass: "Silicates",
    mohsHardnessMin: 6.5,
    mohsHardnessMax: 7.0,
    specificGravity: 3.27,
    luster: "Vitreous",
    color: "Olive-green, yellow-green, pistachio green",
    streak: "White",
    cleavage: "Poor {010} and {100}",
    fracture: "Conchoidal",
    opticalProperties: "Biaxial (+) na=1.636, nb=1.651, ng=1.669",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Distinctive olive green color, granular sugary aggregates, conchoidal fracture, lack of cleavage",
    commonAssociatedRocks: "Peridotite, Dunite, Basalt, Kimberlite, Mantle xenoliths",
    industrialUses: "CO2 carbon mineralization sequestering, Refractory foundry sand, Peridot gemstone",
    occurrence: "Dominant constituent of Earth's upper mantle and primitive komatiitic/basaltic volcanism",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040038",
  },
  {
    name: "Almandine (Garnet)",
    formula: "Fe3Al2(SiO4)3",
    crystalSystem: "Isometric",
    mineralClass: "Silicates",
    mohsHardnessMin: 7.0,
    mohsHardnessMax: 7.5,
    specificGravity: 4.31,
    luster: "Vitreous to resinous",
    color: "Deep red, brownish red, violet red",
    streak: "White",
    cleavage: "None (parting along {110})",
    fracture: "Subconchoidal to uneven",
    opticalProperties: "Isotropic (n = 1.83)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to sub-translucent",
    diagnosticFeatures: "Dodecahedral or trapezohedral crystal forms, hardness 7.5, isotropic optics, deep wine-red color",
    commonAssociatedRocks: "Mica schist, Gneiss, Granulite, Eclogite, Pegmatite",
    industrialUses: "Industrial abrasive (sandblasting & waterjet cutting), Gemstone",
    occurrence: "Regional medium-to-high grade Barrovian metamorphism of pelitic argillaceous rocks",
    imageUrl: "https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040026",
  },
  {
    name: "Zircon",
    formula: "ZrSiO4",
    crystalSystem: "Tetragonal",
    mineralClass: "Silicates",
    mohsHardnessMin: 7.5,
    mohsHardnessMax: 7.5,
    specificGravity: 4.67,
    luster: "Adamantine to vitreous",
    color: "Reddish brown, yellow, green, blue, colorless",
    streak: "White",
    cleavage: "Indistinct {100}",
    fracture: "Conchoidal",
    opticalProperties: "Uniaxial (+) extreme birefringence ne=1.984, nw=1.924",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Tetragonal prism-dipyramid crystal habit, high density (4.67), adamantine luster, high resistance to weathering",
    commonAssociatedRocks: "Granite, Syenite, Pegmatite, Heavy mineral sands, Gneiss",
    industrialUses: "U-Pb Geochronology (Earth's oldest minerals >4.4 Ga), Zirconium metal for nuclear reactors, Refractory opacifier",
    occurrence: "Early accessory magmatic crystallization preserved across repeated sedimentary cycles",
    rruffId: "R040004",
  },
  {
    name: "Kyanite",
    formula: "Al2SiO5",
    crystalSystem: "Triclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 4.5,
    mohsHardnessMax: 7.0,
    specificGravity: 3.61,
    luster: "Vitreous to pearly",
    color: "Sky blue, white, gray, green",
    streak: "White",
    cleavage: "Perfect {100}, good {010}",
    fracture: "Splintery",
    opticalProperties: "Biaxial (-) na=1.712, nb=1.720, ng=1.728",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Bladed blue crystals with distinct anisotropic hardness (4.5 parallel to c-axis; 7.0 perpendicular)",
    commonAssociatedRocks: "Pelitic schist, Gneiss, Eclogite, Quartzite",
    industrialUses: "High-temperature refractory ceramics, Spark plugs, Mullite synthesis",
    occurrence: "High-pressure, medium-temperature regional metamorphism (Barrovian index mineral)",
    rruffId: "R040001",
  },
  {
    name: "Tourmaline (Schorl)",
    formula: "NaFe3Al6(BO3)3Si6O18(OH)4",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Silicates",
    mohsHardnessMin: 7.0,
    mohsHardnessMax: 7.5,
    specificGravity: 3.2,
    luster: "Vitreous to resinous",
    color: "Jet black",
    streak: "White to gray",
    cleavage: "None",
    fracture: "Uneven to conchoidal",
    opticalProperties: "Uniaxial (-) strong dichroism",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Rounded triangular cross-section (Reuleaux triangle), vertical prism striations, lack of cleavage",
    commonAssociatedRocks: "Granite pegmatite, Greisen, Tourmalinite, Hydrothermal vein quartz",
    industrialUses: "Piezoelectric and pyroelectric pressure gauges, Tourmaline ceramics",
    occurrence: "Boron-rich residual pegmatitic fluids and pneumatolytic greisens",
    rruffId: "R040018",
  },
  {
    name: "Beryl (Emerald / Aquamarine)",
    formula: "Be3Al2Si6O18",
    crystalSystem: "Hexagonal",
    mineralClass: "Silicates",
    mohsHardnessMin: 7.5,
    mohsHardnessMax: 8.0,
    specificGravity: 2.76,
    luster: "Vitreous",
    color: "Vivid green (emerald), sea-blue (aquamarine), pink (morganite), yellow (heliodor)",
    streak: "White",
    cleavage: "Imperfect basal {0001}",
    fracture: "Conchoidal to uneven",
    opticalProperties: "Uniaxial (-) nw=1.577, ne=1.571",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Hexagonal hexagonal prismatic crystals, hardness 7.5-8.0, lack of good cleavage",
    commonAssociatedRocks: "Granite pegmatite, Hydrothermal calcite-pyrite veins (Muzo), Phlogopite schist",
    industrialUses: "Beryllium ore (aerospace structural alloys), Precious gemstone",
    occurrence: "Beryllium-rich granitic pegmatites intersecting chromium/vanadium host rocks",
    imageUrl: "https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040023",
  },
  {
    name: "Kaolinite",
    formula: "Al2Si2O5(OH)4",
    crystalSystem: "Triclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 2.0,
    mohsHardnessMax: 2.5,
    specificGravity: 2.63,
    luster: "Dull earthy to pearly",
    color: "White, cream, yellowish",
    streak: "White",
    cleavage: "Perfect basal {001}",
    fracture: "Earthy",
    opticalProperties: "Biaxial (-)",
    imaStatus: "Approved",
    tenacity: "Plastic when wet, brittle when dry",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Soft, chalky feel, clay-like earthy odor when breathed upon, sticks to moist tongue",
    commonAssociatedRocks: "Kaolin clay beds, Weathered granites (saprolite), Hydrothermal alteration halos",
    industrialUses: "Paper coating (gloss), Fine porcelain ceramics, Medicine (kaopectate), Paint extender",
    occurrence: "Intense chemical weathering and hydrothermal argillic alteration of feldspars",
    rruffId: "R040006",
  },
  {
    name: "Talc",
    formula: "Mg3Si4O10(OH)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Silicates",
    mohsHardnessMin: 1.0,
    mohsHardnessMax: 1.0,
    specificGravity: 2.75,
    luster: "Pearly to greasy",
    color: "Apple-green, gray, white, silver-white",
    streak: "White",
    cleavage: "Perfect basal {001}",
    fracture: "Uneven",
    opticalProperties: "Biaxial (-)",
    imaStatus: "Approved",
    tenacity: "Sectile, flexible but non-elastic",
    diaphaneity: "Translucent to sub-translucent",
    diagnosticFeatures: "Mohs hardness 1 (scratched easily by fingernail), extremely greasy/soapy tactile feel",
    commonAssociatedRocks: "Soapstone (steatite), Talc schist, Hydrothermally altered serpentinite",
    industrialUses: "Cosmetics (talcum powder), Paper filler, Ceramics, Lubricant, Plastics reinforcer",
    occurrence: "Hydrothermal alteration of ultramafic magnesium-rich rocks (serpentine, olivine)",
    rruffId: "R040028",
  },

  // --- OXIDES & HYDROXIDES ---
  {
    name: "Hematite",
    formula: "Fe2O3",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Oxides",
    mohsHardnessMin: 5.5,
    mohsHardnessMax: 6.5,
    specificGravity: 5.26,
    luster: "Metallic to earthy dull",
    color: "Steel-gray, reddish brown, black",
    streak: "Characteristic cherry-red to reddish-brown",
    cleavage: "None (rhombohedral parting)",
    fracture: "Uneven to subconchoidal",
    opticalProperties: "Uniaxial (-) opaque",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Unmistakable cherry-red streak regardless of whether specimen is shiny silver or earthy brown",
    commonAssociatedRocks: "Banded Iron Formations (BIF), Hydrothermal veins, Oolitic ironstone, Skarns",
    industrialUses: "Principal ore of iron and steel production, Red pigment (ochre), Polishing rouge",
    occurrence: "Sedimentary marine precipitation (BIFs) and supergene oxidation of iron deposits",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040024",
  },
  {
    name: "Magnetite",
    formula: "Fe3O4",
    crystalSystem: "Isometric",
    mineralClass: "Oxides",
    mohsHardnessMin: 5.5,
    mohsHardnessMax: 6.5,
    specificGravity: 5.18,
    luster: "Metallic to submetallic",
    color: "Iron-black",
    streak: "Black",
    cleavage: "None (octahedral parting)",
    fracture: "Uneven",
    opticalProperties: "Isotropic opaque",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Strongly ferromagnetic (attracted strongly to hand magnet, lodestone variety attracts iron filings)",
    commonAssociatedRocks: "Banded iron formations, Layered mafic intrusions (Bushveld), Skarns, Heavy sand placers",
    industrialUses: "Major iron ore, Dense media separation in coal washing, Magnetic recording media",
    occurrence: "Magmatic fractional segregation in mafic melts and contact metasomatic skarns",
    rruffId: "R040025",
  },
  {
    name: "Corundum (Ruby / Sapphire)",
    formula: "Al2O3",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Oxides",
    mohsHardnessMin: 9.0,
    mohsHardnessMax: 9.0,
    specificGravity: 4.02,
    luster: "Adamantine to vitreous",
    color: "Red (ruby), blue (sapphire), yellow, pink, brown, colorless",
    streak: "White",
    cleavage: "None (rhombohedral and basal parting)",
    fracture: "Conchoidal to uneven",
    opticalProperties: "Uniaxial (-) nw=1.768, ne=1.760",
    imaStatus: "Approved",
    tenacity: "Brittle, very tough",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Hardness 9 (second only to diamond), barrel-shaped hexagonal prisms, parting planes, high specific gravity",
    commonAssociatedRocks: "Syenite, Corundum-nepheline pegmatite, Marble, Alumina-rich schists, Placers",
    industrialUses: "Precious gemstones (Ruby, Sapphire), High-precision watch bearings, Optical laser rods",
    occurrence: "Silica-undersaturated magmas and high-grade contact/regional metamorphism",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040007",
  },
  {
    name: "Cassiterite",
    formula: "SnO2",
    crystalSystem: "Tetragonal",
    mineralClass: "Oxides",
    mohsHardnessMin: 6.0,
    mohsHardnessMax: 7.0,
    specificGravity: 6.98,
    luster: "Adamantine to metallic",
    color: "Black, brownish black, reddish brown ('wood tin')",
    streak: "White to light brownish",
    cleavage: "Imperfect {100}, {110}",
    fracture: "Subconchoidal",
    opticalProperties: "Uniaxial (+) extreme birefringence",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "High density (nearly 7), adamantine luster, elbow/knee-shaped contact twins",
    commonAssociatedRocks: "Greisen, Granite pegmatite, Hydrothermal tin veins, Alluvial placer gravels",
    industrialUses: "Primary global ore of tin (Sn), Solder in electronics, Tin plating",
    occurrence: "Pneumatolytic and hydrothermal greisens associated with highly evolved granites",
    rruffId: "R040017",
  },
  {
    name: "Chromite",
    formula: "FeCr2O4",
    crystalSystem: "Isometric",
    mineralClass: "Oxides",
    mohsHardnessMin: 5.5,
    mohsHardnessMax: 5.5,
    specificGravity: 4.6,
    luster: "Submetallic to pitchy",
    color: "Iron black to brownish black",
    streak: "Dark brown",
    cleavage: "None",
    fracture: "Uneven",
    opticalProperties: "Isotropic opaque",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Submetallic black octahedral grains in ultramafic rocks, brown streak, weakly magnetic",
    commonAssociatedRocks: "Peridotite, Dunite, Serpentinite, Layered ultramafic complexes (Great Dyke, Bushveld)",
    industrialUses: "Sole commercial ore of chromium (stainless steel, superalloys, plating)",
    occurrence: "Early cumulate layers in stratiform mafic-ultramafic layered complexes and ophiolites",
    rruffId: "R040047",
  },

  // --- SULFIDES & ARSENIDES (Ore Minerals) ---
  {
    name: "Pyrite (Fool's Gold)",
    formula: "FeS2",
    crystalSystem: "Isometric",
    mineralClass: "Sulfides",
    mohsHardnessMin: 6.0,
    mohsHardnessMax: 6.5,
    specificGravity: 5.02,
    luster: "Metallic",
    color: "Pale brass-yellow",
    streak: "Greenish-black to brownish-black",
    cleavage: "Indistinct {001}",
    fracture: "Conchoidal to uneven",
    opticalProperties: "Opaque, high reflectance",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Striated cubic and pyritohedral crystal habit, hard (6-6.5, scratches glass, unlike gold), brassy metallic luster",
    commonAssociatedRocks: "Hydrothermal veins, Sedimentary black shales, Coal beds, VMS deposits, Skarns",
    industrialUses: "Source of sulfur for sulfuric acid manufacture, Gold indicator mineral in Carlin-type deposits",
    occurrence: "Ubiquitous sulfide formed in hydrothermal systems and anoxic marine sediments",
    imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=600&q=80",
    rruffId: "R050190",
  },
  {
    name: "Chalcopyrite",
    formula: "CuFeS2",
    crystalSystem: "Tetragonal",
    mineralClass: "Sulfides",
    mohsHardnessMin: 3.5,
    mohsHardnessMax: 4.0,
    specificGravity: 4.28,
    luster: "Metallic",
    color: "Brass yellow, frequently with iridescent rainbow tarnish (peacock ore)",
    streak: "Greenish-black",
    cleavage: "Poor {011}",
    fracture: "Uneven",
    opticalProperties: "Opaque",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Deeper brass-yellow than pyrite, softer (3.5-4, easily scratched by knife), greenish-black streak",
    commonAssociatedRocks: "Porphyry copper, Volcanogenic massive sulfide (VMS), Hydrothermal veins, Skarns",
    industrialUses: "Primary global ore of copper (Cu)",
    occurrence: "Magmatic-hydrothermal porphyry systems and oceanic spreading center black smokers",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040029",
  },
  {
    name: "Galena",
    formula: "PbS",
    crystalSystem: "Isometric",
    mineralClass: "Sulfides",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 2.5,
    specificGravity: 7.58,
    luster: "Bright metallic",
    color: "Lead-gray",
    streak: "Lead-gray",
    cleavage: "Perfect cubic {001} in 3 directions at 90°",
    fracture: "Subconchoidal",
    opticalProperties: "Opaque, isotropic",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Opaque",
    diagnosticFeatures: "High density (7.58), distinct cubic cleavage stepping, lead-gray metallic luster and streak",
    commonAssociatedRocks: "Mississippi Valley-Type (MVT) deposits, Hydrothermal veins, Skarns, Carbonate host rocks",
    industrialUses: "Primary ore of lead (Pb), major source of byproduct silver (Ag), Lead-acid batteries",
    occurrence: "Low-to-medium temperature hydrothermal veins and epigenetic replacements in limestones",
    rruffId: "R040037",
  },
  {
    name: "Sphalerite",
    formula: "(Zn,Fe)S",
    crystalSystem: "Isometric",
    mineralClass: "Sulfides",
    mohsHardnessMin: 3.5,
    mohsHardnessMax: 4.0,
    specificGravity: 4.05,
    luster: "Resinous to adamantine / submetallic",
    color: "Yellow, reddish brown, black ('blackjack')",
    streak: "Pale yellow to brownish white",
    cleavage: "Perfect dodecahedral {110} in 6 directions",
    fracture: "Conchoidal",
    opticalProperties: "Isotropic (n = 2.37)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "6 directions of perfect cleavage, resinous to adamantine luster, sulfurous smell when powdered in HCl",
    commonAssociatedRocks: "Sedex deposits, MVT lead-zinc deposits, VMS, Hydrothermal veins",
    industrialUses: "Chief global ore of zinc (Zn), Source of critical tech elements (Indium, Gallium, Germanium)",
    occurrence: "Hydrothermal polymetallic veins and carbonate replacement ore bodies",
    rruffId: "R040032",
  },
  {
    name: "Molybdenite",
    formula: "MoS2",
    crystalSystem: "Hexagonal",
    mineralClass: "Sulfides",
    mohsHardnessMin: 1.0,
    mohsHardnessMax: 1.5,
    specificGravity: 4.73,
    luster: "Metallic",
    color: "Lead-gray with bluish tinge",
    streak: "Greenish gray on porcelain (distinguishes from graphite)",
    cleavage: "Perfect basal {0001}",
    fracture: "Uneven",
    opticalProperties: "Opaque, extreme bireflectance",
    imaStatus: "Approved",
    tenacity: "Flexible, sectile, greasy feel",
    diaphaneity: "Opaque",
    diagnosticFeatures: "Very soft (1-1.5), greasy feel, bluish-lead gray color, leaves greenish mark on porcelain streak plate",
    commonAssociatedRocks: "Porphyry molybdenum, Porphyry Cu-Mo, Greisens, High-temperature quartz veins",
    industrialUses: "Primary ore of molybdenum (high-strength steel alloys), High-temperature dry lubricant",
    occurrence: "High-temperature hydrothermal systems associated with granitic-rhyolitic porphyries",
    rruffId: "R040051",
  },

  // --- CARBONATES ---
  {
    name: "Calcite",
    formula: "CaCO3",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Carbonates",
    mohsHardnessMin: 3.0,
    mohsHardnessMax: 3.0,
    specificGravity: 2.71,
    luster: "Vitreous to pearly",
    color: "Colorless, white, yellow, orange, blue, pink",
    streak: "White",
    cleavage: "Perfect rhombohedral {1011} in 3 directions at 74°55'",
    fracture: "Conchoidal",
    opticalProperties: "Uniaxial (-) strong double refraction (Iceland spar)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Vigorous effervescence in cold dilute 10% HCl, hardness 3, perfect rhombohedral cleavage, strong birefringence",
    commonAssociatedRocks: "Limestone, Marble, Chalk, Carbonatite, Cave speleothems, Hydrothermal veins",
    industrialUses: "Portland cement, Agricultural lime, Chemical manufacturing, Optical polarizers",
    occurrence: "Marine biogenic sedimentation, regional metamorphism, and carbonatite volcanism (e.g. Ol Doinyo Lengai)",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040016",
  },
  {
    name: "Dolomite",
    formula: "CaMg(CO3)2",
    crystalSystem: "Hexagonal (Trigonal)",
    mineralClass: "Carbonates",
    mohsHardnessMin: 3.5,
    mohsHardnessMax: 4.0,
    specificGravity: 2.85,
    luster: "Vitreous to pearly",
    color: "White, pinkish, cream, tan",
    streak: "White",
    cleavage: "Perfect rhombohedral {1011}",
    fracture: "Subconchoidal",
    opticalProperties: "Uniaxial (-)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Saddle-shaped curved rhombohedral crystals, effervesces in warm HCl or only when finely powdered in cold HCl",
    commonAssociatedRocks: "Dolostone (dolomitic limestone), Hydrothermal alteration halos, Skarns",
    industrialUses: "Magnesium source, Refractory furnace bricks, Road aggregate, Soil conditioning",
    occurrence: "Diagenetic dolomitization of marine limestone platforms by magnesium-rich fluids",
    rruffId: "R040030",
  },
  {
    name: "Malachite",
    formula: "Cu2(CO3)(OH)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Carbonates",
    mohsHardnessMin: 3.5,
    mohsHardnessMax: 4.0,
    specificGravity: 4.05,
    luster: "Adamantine to silky / dull",
    color: "Bright emerald green to dark green with concentric banding",
    streak: "Pale green",
    cleavage: "Perfect {201}",
    fracture: "Subconchoidal to splintery",
    opticalProperties: "Biaxial (-) strong pleochroism",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Vivid bright green color, botryoidal concentric banding, effervescence in dilute HCl",
    commonAssociatedRocks: "Supergene oxidation zones of copper deposits (gossans), Sandstone copper",
    industrialUses: "Minor copper ore, Gemstone, Ornamental carving, Historical green mineral pigment",
    occurrence: "Supergene weathering of primary copper sulfides (chalcopyrite, bornite) in carbonate hosts",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80",
    rruffId: "R050041",
  },
  {
    name: "Azurite",
    formula: "Cu3(CO3)2(OH)2",
    crystalSystem: "Monoclinic",
    mineralClass: "Carbonates",
    mohsHardnessMin: 3.5,
    mohsHardnessMax: 4.0,
    specificGravity: 3.77,
    luster: "Vitreous to adamantine",
    color: "Deep azure blue to dark blue",
    streak: "Light blue",
    cleavage: "Perfect {011}, fair {100}",
    fracture: "Conchoidal",
    opticalProperties: "Biaxial (+)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Translucent to opaque",
    diagnosticFeatures: "Intense azure-blue color, light blue streak, effervesces in HCl, associated with green malachite",
    commonAssociatedRocks: "Oxidized copper zones, Gossans, Carbonate-hosted copper deposits",
    industrialUses: "Copper exploration indicator mineral, Ornamental gemstone, Blue pigment",
    occurrence: "Secondary supergene mineral formed in the vadose zone of copper deposits",
    rruffId: "R040050",
  },

  // --- HALIDES, SULFATES & PHOSPHATES ---
  {
    name: "Halite (Rock Salt)",
    formula: "NaCl",
    crystalSystem: "Isometric",
    mineralClass: "Halides",
    mohsHardnessMin: 2.5,
    mohsHardnessMax: 2.5,
    specificGravity: 2.16,
    luster: "Vitreous",
    color: "Colorless, white, blue, purple, pink",
    streak: "White",
    cleavage: "Perfect cubic {001} in 3 directions at 90°",
    fracture: "Conchoidal",
    opticalProperties: "Isotropic (n = 1.544)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Salty taste, perfect cubic cleavage, easily dissolved in water, low hardness (2.5)",
    commonAssociatedRocks: "Evaporite salt beds, Salt domes, Playa lake deposits",
    industrialUses: "Chemical manufacturing (Chlorine, Caustic soda), Food seasoning, De-icing",
    occurrence: "Evaporation of restricted marine basins and continental playa lakes",
    rruffId: "R040065",
  },
  {
    name: "Fluorite",
    formula: "CaF2",
    crystalSystem: "Isometric",
    mineralClass: "Halides",
    mohsHardnessMin: 4.0,
    mohsHardnessMax: 4.0,
    specificGravity: 3.18,
    luster: "Vitreous",
    color: "Purple, green, yellow, blue, pink, colorless",
    streak: "White",
    cleavage: "Perfect octahedral {111} in 4 directions",
    fracture: "Subconchoidal",
    opticalProperties: "Isotropic (n = 1.434)",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Mohs hardness 4 index, 4 directions of perfect octahedral cleavage, strong UV fluorescence",
    commonAssociatedRocks: "Hydrothermal veins, Granitic greisens, Carbonate Mississippi Valley type replacements",
    industrialUses: "Metallurgical flux in steelmaking, Hydrofluoric acid synthesis, Optical lenses",
    occurrence: "Hydrothermal veins and metasomatic replacement bodies",
    imageUrl: "https://images.unsplash.com/photo-1596541223130-5d31a73fb6c6?auto=format&fit=crop&w=600&q=80",
    rruffId: "R040034",
  },
  {
    name: "Gypsum",
    formula: "CaSO4·2H2O",
    crystalSystem: "Monoclinic",
    mineralClass: "Sulfates",
    mohsHardnessMin: 2.0,
    mohsHardnessMax: 2.0,
    specificGravity: 2.32,
    luster: "Vitreous to pearly / silky (satin spar)",
    color: "Colorless (selenite), white, yellowish, pink",
    streak: "White",
    cleavage: "Perfect {010}, distinct {100} and {011}",
    fracture: "Splintery / conchoidal",
    opticalProperties: "Biaxial (+)",
    imaStatus: "Approved",
    tenacity: "Flexible, non-elastic, sectile",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Mohs hardness 2 (easily scratched by fingernail), pearly luster on folia, sectility",
    commonAssociatedRocks: "Evaporite beds, Sedimentary shale caprocks, Fumarolic sublimates",
    industrialUses: "Plaster of Paris, Drywall / Gypsum board, Soil conditioning, Retarder in cement",
    occurrence: "Precipitation in evaporating saline seawater and playa lakes",
    rruffId: "R040027",
  },
  {
    name: "Apatite",
    formula: "Ca5(PO4)3(F,Cl,OH)",
    crystalSystem: "Hexagonal",
    mineralClass: "Phosphates",
    mohsHardnessMin: 5.0,
    mohsHardnessMax: 5.0,
    specificGravity: 3.19,
    luster: "Vitreous to subresinous",
    color: "Green, blue, violet, brown, colorless",
    streak: "White",
    cleavage: "Indistinct basal {0001}",
    fracture: "Conchoidal to uneven",
    opticalProperties: "Uniaxial (-) nw=1.633, ne=1.630",
    imaStatus: "Approved",
    tenacity: "Brittle",
    diaphaneity: "Transparent to translucent",
    diagnosticFeatures: "Mohs hardness 5 index (scratched by pocketknife), hexagonal prismatic crystals with basal pinacoid",
    commonAssociatedRocks: "Carbonatites, Phosphorite beds, Granite pegmatite, Calc-silicate skarns",
    industrialUses: "Primary global source of phosphorus for agricultural fertilizers, Bio-ceramics (bone hydroxyapatite)",
    occurrence: "Igneous carbonatites and marine sedimentary phosphorite deposits",
    rruffId: "R040002",
  },
];

/**
 * Upserts the curated mineral dataset into PostgreSQL
 */
export async function syncMineralDatabase(): Promise<{ addedOrUpdated: number }> {
  let count = 0;
  for (const item of CURATED_MINERAL_DATASET) {
    const [existing] = await refDb
      .select({ id: minerals.id })
      .from(minerals)
      .where(eq(minerals.name, item.name))
      .limit(1);

    if (existing) {
      await refDb
        .update(minerals)
        .set({
          ...item,
          updatedAt: new Date(),
        })
        .where(eq(minerals.id, existing.id));
    } else {
      await refDb.insert(minerals).values({
        ...item,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
    }
    count++;
  }
  return { addedOrUpdated: count };
}

/**
 * Starts the nightly background timer scheduled for 00:00 EAT (21:00 UTC)
 */
export function startNightlyMineralSyncCron() {
  const checkIntervalMs = 60 * 1000; // Check every 60 seconds

  setInterval(() => {
    const now = new Date();
    const utcHours = now.getUTCHours();
    const utcMinutes = now.getUTCMinutes();

    // 21:00 UTC == 00:00 EAT (Kenyan Time / Midnight)
    if (utcHours === 21 && utcMinutes === 0) {
      console.log("🕒 [00:00 EAT Midnight Cron] Triggering Scheduled Minerals Database & Sourcing Pipeline...");
      syncMineralDatabase().then(({ addedOrUpdated }) => {
        console.log(`✅ [00:00 EAT Midnight Cron] Synced and validated ${addedOrUpdated} mineral species in database.`);
      }).catch((err) => {
        console.warn("⚠️ [00:00 EAT Midnight Cron] Mineral sync warning:", err.message);
      });
    }
  }, checkIntervalMs);
}
